version: "3.9"

services:
  bkpoltinove:
    build: .
    container_name: bkpoltinove
    network_mode: "host"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /home/inove:/app
      - /home/inove/logs:/app/logs
      - /home/inove/backups:/app/backups
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Bahia
